# Steps to enable this build are:
#
# Generate the OAUTH-TOKEN atd at https://github.com/settings/applications
# Install travis: gem install travis
# Login to travis: travis login
# Encrypt the token: travis encrypt GH_TOKEN=[OAUTH-TOKEN] -r Intenet2/grouper --add env.global
#

language: java
sudo: false
branches:
  only:
  - gradle
jdk:
  - oraclejdk7
cache:
  directories:
    - '$HOME/.gradle/caches'
env:
  global:
    - secure: "XmmxnbDo/FeIE2O5M6YMSKjULOgLPDDx79mcfRTf79Fvjiqw2yJBrheLwR2sYs4+6uw7Pe0FkKUXtyRrcK31JvWTuqvwTs08MgMt42VPx7xGX+96i8hN6QTF8D1B1YYRJnnXrtOrhqSbpm+jffw3PiK4f5fcKDntSaMbPUiVRDg="
    - secure: "MjJBfBqMpetCZ0PmcISetMxHAEcC83EawXmJuCW/F7RrCk8tBY+YglYSRHFqj/LDcwLHdDPuPOLHEv/RKPyqQvjYfJICwpQugMRrIUPuoXsg57xoSP36DBNG8qVCa5rS1qLaUb42fsvYXd9ufjKu8c0Eihq8pbz+yrXxKgvSpIU="
    - secure: "kJDUzde56X0epK70R9e2hN7Q6nfHyk0ixDOynPYJh01hREyLl/7Zm3V6dv5nfGhFbCoJDcqkTlUsl26ixrmmr4AUhh+fKkQVO8Pjj8z9fR6Y1lukJ2v2RVDRzN0sR5cCqKGd2yr9VW9s+4JinfcBQNj2dxwhCKddj+NPPM9o0CE="
before_script:
 - export JAVA_OPTS="-Xmx2048m"
before_install:
- chmod -R 777 ./travis/init-travis-build.sh
- ./travis/init-travis-build.sh
- chmod -R 777 ./gradlew
install:
- ./gradlew clean --parallel --stacktrace 
script:
- travis_wait ./gradlew build javadoc -x test --parallel --stacktrace
after_success:
- chmod -R 777 travis/javadocs-ghpages.sh
- travis/javadocs-ghpages.sh
- chmod -R 777 travis/deploy-to-sonatype.sh
- travis/deploy-to-sonatype.sh
