# Steps to enable this build are:
#
# Generate the OAUTH-TOKEN atd at https://github.com/settings/applications
# Install travis: gem install travis
# Login to travis: travis login
# Encrypt the token: travis encrypt GH_TOKEN=[OAUTH-TOKEN] -r Intenet2/grouper --add env.global
#

language: java
branches:
  only:
  - master
  - GROUPER_2_1_BRANCH
  - GROUPER_2_2_BRANCH
jdk:
- oraclejdk7
- openjdk6
- openjdk7
- oraclejdk8
before_script:
- cd grouper-parent
install:
- cd grouper-parent
- mvn install -Dmaven.javadoc.skip=true -DskipTests=true -Dlicense.skip=true -B -V -q 
script:
- mvn clean package -DskipTests=true -Dlicense.skip=true
before_install:
- chmod -R 777 ./travis/init-travis-build.sh
- ./travis/init-travis-build.sh
after_success:
- mvn clean test cobertura:cobertura coveralls:cobertura
- cd ..
- chmod -R 777 travis/javadocs-ghpages.sh
- travis/javadocs-ghpages.sh
env:
  global:
    secure: XmmxnbDo/FeIE2O5M6YMSKjULOgLPDDx79mcfRTf79Fvjiqw2yJBrheLwR2sYs4+6uw7Pe0FkKUXtyRrcK31JvWTuqvwTs08MgMt42VPx7xGX+96i8hN6QTF8D1B1YYRJnnXrtOrhqSbpm+jffw3PiK4f5fcKDntSaMbPUiVRDg=
