# Steps to enable this build are:
#
# Generate the OAUTH-TOKEN atd at https://github.com/settings/applications
# Install travis: gem install travis
# Login to travis: travis login
# Encrypt the token: travis encrypt GH_TOKEN=[OAUTH-TOKEN] -r Intenet2/grouper --add env.global
#

language: java
sudo: false
branches:
  only:
  - gradle
jdk:
  - oraclejdk7
cache:
  directories:
    - '$HOME/.gradle/caches'
env:
  global:
    secure: XmmxnbDo/FeIE2O5M6YMSKjULOgLPDDx79mcfRTf79Fvjiqw2yJBrheLwR2sYs4+6uw7Pe0FkKUXtyRrcK31JvWTuqvwTs08MgMt42VPx7xGX+96i8hN6QTF8D1B1YYRJnnXrtOrhqSbpm+jffw3PiK4f5fcKDntSaMbPUiVRDg=
before_install:
- chmod -R 777 ./travis/init-travis-build.sh
- ./travis/init-travis-build.sh
- chmod -R 777 ./gradlew
install:
- ./gradlew clean
script:
- ./gradlew build -x javadoc -x test --parallel --stacktrace
after_success:
# - chmod -R 777 travis/javadocs-ghpages.sh
# - travis/javadocs-ghpages.sh
